dependencies:
  /content/pages/about.md:
  - /content/pages/about.md
  - /content/pages/home.yaml
  - /content/pages/projects.md
  - /dist/css/composite/global.min.css
  - /dist/js/composite/global.min.js
  - /partials/footer/footer.html
  - /partials/header/header.html
  - /static/images/favicon.png
  /content/pages/home.yaml:
  - /content/pages/about.md
  - /content/pages/home.yaml
  - /content/pages/projects.md
  - /dist/css/composite/global.min.css
  - /dist/css/composite/home.min.css
  - /dist/js/composite/global.min.js
  - /dist/js/composite/home.min.js
  - /partials//views/partials/hero.html//views/partials/hero.html.html
  - /partials/footer/footer.html
  - /partials/header/header.html
  - /partials/hero/hero.html
  - /static/images/favicon.png
  /content/pages/projects.md:
  - /content/pages/about.md
  - /content/pages/home.yaml
  - /content/pages/projects.md
  - /dist/css/composite/global.min.css
  - /dist/js/composite/global.min.js
  - /partials/footer/footer.html
  - /partials/header/header.html
  - /static/images/favicon.png
objects: {}
